FORMAT: 1A
HOST: https://naturenet-staging.firebaseio.com

# NatureNet

NatureNet is a citizen science project with a crowd-sourced design.
The goal to increase motivation for participation and to identify
creative ways in which people can contribute to sustainable bio-diversity.

----

# Group Existing API

The section documents the existing API and data model.

## Data Model

> Can someone more familiar with how `Note`'s are structured fill this in?
>
> -- Jason

----

# Group Proposed API

This section describes the API we want post refactor/migration. Where possible when describing a
new endpoint include how/if the results could be obtained by having the server do a transformation
on the existing data model.

## Data Model

```
+----------------------+                      +----------------------+                  +---------------------+
|                      |                      |                      |                  |                     |
|   SITE               |                      |   ACTIVITY           |                  |   OBSERVATION       |
|   * id         <------------------+         |   * id          <---------+             |   * id              |
|   * name             |            |         |   * [sites]          |    |             |   * activity        |
|   * description      |            +------------+  * site_id   <------+  +---------------+   * activity_id   |
|   * location         |                      |     * location       | +------------------+   * site_id       |
|                      |                      |   * name             |                  |   * location        |
|                      |                      |   * description      |     +--------------+ * observer_id     |
+----------------------+                      |   * icon_url         |     |            |   * data            |
                                              |   * markup           |     |            |   * [comments]      |
                                              |                      |     |            |     * id            |
                                              |                      |     +--------------+   * commenter_id  |
                                              +----------------------+     |            |     * comment       |
                                                                           |            |                     |
                                                                           |            |                     |
+----------------------+                      +----------------------+     |            +---------------------+
|                      |                      |                      |     |
|   IDEA               |                      |   USER               |     |
|   * id               |    +-------------------> * id        <------------+
|   * submitter_id  +-------+                 |   * display_name     |
|   * group            |    |                 |   * email            |
|   * content          |    |                 |   * account          |
|   * icon_url         |    |                 |     * type           |
|   * [comments]       |    |                 |     * credentials    |
|     * id             |    |                 |       * {mixed}      |
|     * commenter_id +------+                 |   * avatar_url       |
|     * comment        |                      |   * consent_text     |
|                      |                      |   * affiliation      |
|                      |                      |                      |
+----------------------+                      |                      |
                                              +----------------------+
```

In comparison to the deeply nested way the data is stored now we can break it out into different models.
This lets us use nesting where appropriate, `SITE::activities` and `IDEAS::comments` are goods fits,
but use relations elswhere to we can avoid the problem we have now of having to wait ~9s for an observation
view to load because so much extraneous data is loaded.

*See the `Data Structures` section in the markdown for more details (it doesn't get rendered
into the main docs)*.

*Assume all records have timestamp fields `created_at` and `updated_at` in addition to those listed*

### Activity::markup

Each activity is potentially unique in how many and what types of observations it wants the user
to perform. Currently the iOS client (at least) has each different type of observation baked into
it as a different view. When a user selects the activity it does a lookup on the type and loads the
correct native view.

This will end up requiring a unique implementation of the view per platform, per activity. As more
sites and more activities and/or new observation types are created the work to support them is multiplied
by the number of platforms we have clients for.

Instead of doing this we could have each activity specify in markup the types of controls it uses and
their layout. For example:

```html
<activity id="33">
  <section name="about">
    <label>About this activity</label>
    <p>
      The mallard is a species of duck found throughout North America,
      Europe and Asia. They are a common sight at Hallam Lake and in
      any wetland habitat throughout the Aspen area. They are called
      “dabbling” ducks as they feed by tipping forwards in the water
      in order to feed on underwater plants. The males can be identified
      by their iridescent green head and bright yellow bill, while
      females and juveniles are mottled brown with orangey-brown bills.
      How many of each can you see on Hallam Lake today?
    </p>
  </section>
  <section name="males">
    <label>Male Mallard</label>
    <photo-select id="male-malard-count">
      <image url="https://nature-net.org/api/images/that-mallard-1.jpg"/>
      <select caption="Today">
        <choice>0</choice>
        <choice>1</choice>
        <choice>2</choice>
        <choice>3</choice>
        <!-- imagine this goes up to 20 -->
      </select>
    </photo-select>
    <footer>
      <!-- Calls a stored query on the server to return the averages for the day -->
      <p>Daily average this season: <span data-method="https://nature-net.org/api/activity/33/action/1" data-placeholder="--"></span></p>
    </footer>
  </section>
  <section name="females">
    <label>Female Mallard</label>
    <photo-select>
      <image url="https://nature-net.org/api/images/that-mallard-2.jpg"/>
      <select caption="Today">
        <choice>0</choice>
        <choice>1</choice>
        <choice>2</choice>
        <choice>3</choice>
        <!-- imagine this goes up to 20 as well -->
      </select>
    </photo-select id="female-malard-count">
    <footer>
      <!-- Calls a stored query on the server to return the averages for the day -->
      <p>Daily average this season: <span data-method="https://nature-net.org/api/activity/33/action/2" data-placeholder="--"></span></p>
    </footer>
  </section>
  <section>
    <note-input id="notes">Notes</note-input>
  </section>
</activity>
```

This lets us avoid having to write new native client code for each new activity is one of two ways.

1. The above code combined with angularjs directives could be rendered directly into a `WebView`.
    With this approach all clients can share exactly the same code base +/- some setup code.
2. Each client can maintain a library of native controls for each element type. Then the markup
   could be parsed by the client and a native layout created dynamically and presented.

This also allows us to change the way an activity is presented to users without the need to push
new versions of the client and opens the door for sites to create new activities on their own.

### Observation::data

The result of the freeform nature of activities is that each observation will also need to record
different data depening on what activity it was for. We can take a similar approach in storing the
data with a structure that matches up to the markup for the activity. For example an observation
for the above activity could store it's data like this:

```json
{
    "male-malard-count": 3,
    "female-malard-count": 5,
    "notes": "I saw a lot of birds!"
}
```

This solves the same problem for how to render the observation for later viewing. We can take the
same markup that would produce the activity view and insert the stored data into the correct
places.

### Data Structures

#### Site (object)

+ id (required) - unique id for the site
+ name (string, required) - the name of the site for display
+ description (string, required) - a description of the site
+ location (object, required) - a central location for the whole site
    + latitude (number)
    + longitude (number)
+ activities (array, required) - all activities available at this site, may be empty
    + id - unique id for the activity, composite of the site_id and the position in the activities array
    + name (string) - the name of the activity
    + description (string) - a description of the activity
    + location (object, optional) - a specific location for the activity separate from the site
        + latitude (number)
        + longitude (number)
    + icon_url (string) - location of the icon for this activity
    + markup (string) - see markup/data section

#### User

+ id (required) - unique id for the user
+ display_name (string, required) - the name the user wants displayed on their posts
+ account_type (object, required) - the login account type of the user
+ username (string, required) - the username for login purposes, content depends on account type
+ password_hash (string, required) - stored hash of the users password if their account is local
+ password_salt (string, required) - user-unique salt used to generate the hash
+ email (string, required) - the users email address
+ avatar_url (string, required) - location of the users avatar image
+ content_text (string, required) - the text of the consent form this user accepted
+ affiliation (object, optional)

#### Observation

+ id (required) - unique id for the observation
+ activity_id (required) - the id of the activity this observation is for
+ location (object, optional) - the location where the observation was made
    + latitude (number)
    + longitude (number)
+ observer_id (required) - the id of the user who made the observation
+ data (object, required) - see the markup/data section

#### Idea

+ id (required) - unique id for the idea
+ submitter_id (required) - the id of the user who submitted the idea
+ group (string, required) - the group into which the idea was submitted
+ idea (string, required) - the description of the idea
+ icon_url (string, required) - location of the icon for this idea
+ comments (array, required) - any comments on this idea, may be empty
    + id - unique id of the comment
    + commenter_id - the id of the user who made the comment
    + comment (string) - the text of the comment

## Sites [/sites]

Endpoints for loading site and activity data. Currently there is no way to create new sites or
data via this API.

+ Attributes (Site)

### List Sites [GET /sites]

List all the sites. The response will include the nested activities for each site but will strip out
the `markup` attribute.

+ Response 200 (application/json)

        [
            {
            "id": 1,
            "name": "ACES",
            "description": "Aspen Center for Environmental Studies (ACES)",
            "location":
                {
                    "latitude": 39.1965355,
                    "longitude": -106.8242489
                },
            "activities":
                [
                    {
                        "id": 1,
                        "name": "Count the Mallards",
                        "description": "words words words...",
                        "location":
                            {
                                "latitude": 39.1965355,
                                "longitude": -106.8242489
                            },
                        "icon_url": "about:blank"
                    }
                ]
            },
            {
            "id": 2,
            "name": "RNCP",
            "description": "RNCP
            "location":
                {
                    "latitude": 39.1965355,
                    "longitude": -106.8242489
                },
            "activities": []
            }
        ]

### Read Site [GET /site/{id}]

Loads a single site including it's complete activites list.

+ Parameters
    + id: `1` (required) - the id of the site to load

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "ACES",
            "description": "Aspen Center for Environmental Studies (ACES)",
            "location":
                {
                    "latitude": 39.1965355,
                    "longitude": -106.8242489
                },
            "activities":
                [
                    {
                        "id": 1,
                        "name": "Count the Mallards",
                        "description": "words words words...",
                        "location":
                            {
                                "latitude": 39.1965355,
                                "longitude": -106.8242489
                            },
                        "icon_url": "about:blank",
                        "markup": "<content/>"
                    }
                ]
            }


### Read Activity [GET /site/{siteId}/activities/{activityId}]

Loads a single activity.

+ Parameters
    + siteId: `1` (required) - the id of the site to load
    + activityId: `1` (required) - the id of the activity to load

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Count the Mallards",
            "description": "words words words...",
            "location":
                {
                    "latitude": 39.1965355,
                    "longitude": -106.8242489
                },
            "icon_url": "about:blank",
            "markup": "<content/>"
        }

## Observations [/observations]

Endpoints for performing CRUD operations on `Observation`s. All read operations can be performed
without authentication but all create/update/delete actions require a logged in user. All list
operations return the most recent records first.

+ Attributes (Observation)

### List Observations For User [GET /observations/user/{id}{?offset}{?limit}]

Lists all observations submitted by a user.

+ Parameters
    + id: `1` (required) - the id of the user to find observations for
    + offset: `10` (number, optional) - how far into the result set to start from.
        + default: `0`
    + limit: `5` (number, optional) - how many records to return from the offset.

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "activity_id": 1,
                "location":
                    {
                        "latitude": 39.1965355,
                        "longitude": -106.8242489
                    },
                "observer_id": 1,
                "data":
                    {
                        "male-malard-count": 3,
                        "female-malard-count": 5,
                        "notes": "I saw a lot of birds!"
                    }
            }
        ]

### List Observations For Activity [GET /observations/activity/{id}{?offset}{?limit}]

List all the observations submitted for an activity.

+ Parameters
    + id: `1` (required) - the id of the activity to find observations for
    + offset: `10` (number, optional) - how far into the result set to start from.
        + default: `0`
    + limit: `5` (number, optional) - how many records to return from the offset.

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "activity_id": 1,
                "location":
                    {
                        "latitude": 39.1965355,
                        "longitude": -106.8242489
                    },
                "observer_id": 1,
                "data":
                    {
                        "male-malard-count": 3,
                        "female-malard-count": 5,
                        "notes": "I saw a lot of birds!"
                    }
            }
        ]

### List Observations For Site [GET /observations/site/{id}{?offset}{?limit}]

List all the observations submitted for any activity in a site.

+ Parameters
    + id: `1` (required) - the id of the site to find observations for
    + offset: `10` (number, optional) - how far into the result set to start from.
        + default: `0`
    + limit: `5` (number, optional) - how many records to return from the offset.

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "activity_id": 1,
                "location":
                    {
                        "latitude": 39.1965355,
                        "longitude": -106.8242489
                    },
                "observer_id": 1,
                "data":
                    {
                        "male-malard-count": 3,
                        "female-malard-count": 5,
                        "notes": "I saw a lot of birds!"
                    }
            }
        ]

### Read Observation [GET /observations/{id}]

+ Parameters
    + id: `1` (required) - the id of the observation to fetch

+ Response 200 (application/json)

### Create Observation [POST /observations]

+ Request (application/json)

    + Headers

            Cookie: nn-session-id:12345;nn-device-id:67890

    + Body

            {
                "activity_id": 1,
                "location": {"latitude": 10, "longitude": 10},
                "data":
                {
                    "male-malard-count": 3,
                    "female-malard-count": 5,
                    "notes": "I saw a lot of birds!"
                }
            }

+ Response 201 (application/json)

        {
            "id": 1,
            "activity_id": 1,
            "location": {"latitude": 10, "longitude": 10},
            "observer_id": 1,
            "data":
            {
                "male-malard-count": 3,
                "female-malard-count": 5,
                "notes": "I saw a lot of birds!"
            }
        }

+ Response 401 (application/json)

        {
            "status": 401,
            "message": "You must be logged on to create an observation"
        }


### Update Observation [PUT /observations/{id}]

+ Parameters
    + id: `1` (required) - the id of the observation to update

+ Request (application/json)

    + Headers

            Cookie: nn-session-id:12345;nn-device-id:67890

    + Body

            {
                "location": {"latitude": 20, "longitude": 11},
                "data":
                {
                    "male-malard-count": 5,
                    "female-malard-count": 3,
                    "notes": "I saw a lot of not-birds!"
                }
            }

+ Response 200 (application/json)

        {
            "id": 1,
            "activity_id": 1,
            "location": {"latitude": 20, "longitude": 11},
                "data":
                {
                    "male-malard-count": 5,
                    "female-malard-count": 3,
                    "notes": "I saw a lot of not-birds!"
                }
        }

+ Response 401 (application/json)

        {
            "status": 401,
            "message": "You must be logged on to modify an observation"
        }

+ Response 403 (application/json)

        {
            "status": 401,
            "message": "Cannot modify another users observations"
        }

### Delete Observation [DELETE /observations/{id}]

+ Parameters
    + id: `1` (required) - the id of the observation to update

+ Request

    + Headers

            Cookie: nn-session-id:12345;nn-device-id:67890

+ Response 200

+ Response 401 (application/json)

        {
            "status": 401,
            "message": "You must be logged on to delete an observation"
        }

+ Response 403 (application/json)

        {
            "status": 401,
            "message": "Cannot delete another users observations"
        }

## Ideas [/ideas]

Endpoints for performing CRUD operations on `Idea`s. All read operations can be performed
without authentication but all create/update/delete actions require a logged in user.
Commenting on an idea also requires a logged in user. All list operations return the most
recent records first.

+ Attributes (Idea)

### List Ideas [GET /ideas{?offset}{?limit}]

List all ideas that have been submitted.

+ Parameters
    + offset: `10` (number, optional) - how far into the result set to start the list from.
        + Default: `0`
    + limit: `5` (number, optional) - how many records to return from the offset.

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "submitter_id": 1,
                "group": "Wouldn't it be cool if...",
                "content": "Writing the docs made the API happen?",
                "icon_url": "about:blank",
                "comments": []
            }
        ]

### List Ideas For User [GET /ideas/user/{id}{?offset}{?limit}]

List all ideas submitted by a user.

+ Parameters
    + id: `1` (number, required) - the id of the user to fetch ideas for
    + offset: `10` (number, optional) - how far into the result set to start the list from.
        + Default: `0`
    + limit: `5` (number, optional) - how many records to return from the offset.

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "submitter_id": 1,
                "group": "Wouldn't it be cool if...",
                "content": "Writing the docs made the API happen?",
                "icon_url": "about:blank",
                "comments": []
            }
        ]

### Read Idea [GET /ideas/{id}]

+ Parameters
    + id: `1` (number, required) - the id of the idea

+ Response 200 (application/json)

        {
            "id": 1,
            "submitter_id": 1,
            "group": "Wouldn't it be cool if...",
            "content": "Writing the docs made the API happen?",
            "icon_url": "about:blank",
            "comments": []
        }

### Create Idea [POST /ideas]

+ Request

    + Headers

            Cookie: nn-session-id:12345;nn-device-id:67890

    + Body

            {
                "group": "Wouldn't it be cool if...",
                "content": "Writing the docs made the API happen?",
                "icon_url": "about:blank"
            }

+ Response 201 (application/json)

        {
            "id": 1,
            "submitter_id": 1,
            "group": "Wouldn't it be cool if...",
            "content": "Writing the docs made the API happen?",
            "icon_url": "about:blank",
            "comments": []
        }

+ Response 401 (application/json)

        {
            "status": 401,
            "message": "You must be logged on to create an idea"
        }

### Update Idea [PUT /ideas/{id}]

+ Parameters
    + id: `1` (number, required) - the id of the idea

+ Request

    + Headers

            Cookie: nn-session-id:12345;nn-device-id:67890

    + Body

            {
                "group": "Wouldn't it be cool if...",
                "content": "You could update things",
            }

+ Response 200 (application/json)

        {
            "id": 1,
            "submitter_id": 1,
            "group": "Wouldn't it be cool if...",
            "content": "You could update things",
            "icon_url": "about:blank",
            "comments": []
        }

+ Response 401 (application/json)

        {
            "status": 401,
            "message": "You must be logged on to create an idea"
        }

+ Response 401 (application/json)

        {
            "status": 403,
            "message": "You cannot modify another users ideas"
        }


### Delete Idea [DELETE /ideas/{id}]

+ Parameters
    + id: `1` (number, required) - the id of the idea

+ Request

    + Headers

            Cookie: nn-session-id:12345;nn-device-id:67890

+ Response 200 (application/json)

+ Response 401 (application/json)

        {
            "status": 401,
            "message": "You must be logged on to delete an idea"
        }

+ Response 403 (application/json)

        {
            "status": 403,
            "message": "You cannot delete another users ideas"
        }

### Comment On Idea [POST /ideas/{id}/comment]

+ Parameters
    + id: `1` (number, required) - the id of the idea

+ Request

    + Headers

            Cookie: nn-session-id:12345;nn-device-id:67890

    + Body

            {
                "comment": "+1",
            }

+ Response 201 (application/json)

        {
            "id": 1,
            "submitter_id": 1,
            "group": "Wouldn't it be cool if...",
            "content": "Writing the docs made the API happen?",
            "icon_url": "about:blank",
            "comments":
                [
                    {
                        "id": 1,
                        "commenter_id": 2,
                        "comment": "+1"
                    }
                ]
        }

+ Response 401 (application/json)

        {
            "status": 401,
            "message": "You must be logged on to comment on an idea"
        }

## Users [/users]

Endpoints for handling user signup and login.

### Signup [POST /users/signup]

Creates a new user

+ Request (application/json)

    + Body

            {
                "username": "jason",
                "display_name": "Jason Maher",
                "email": "jason@jasonmaher.me",
                "password": "secret",
                "avatar_url": "about:blank"
            }

+ Response 201 (application/json)

    + Headers

            Set-Cookie: nn-session-id:12345;nn-device-id:67890

    + Body

            {
                "id": 1,
                "username": "jason",
                "display_name": "Jason Maher",
                "email": "jason@jasonmaher.me",
                "avatar_url": "about:blank"
            }

+ Response 401 (application/json)

        {
            "status": 401,
            "message": "Username 'jason' is already in use"
        }

+ Response 401 (application/json)

        {
            "status": 401,
            "message": "A user with that email address already exists"
        }

+ Response 401 (application/json)

        {
            "status": 401,
            "message": "Password does not meet critera",
            "errors":
                [
                    "Too short"
                ]
        }

### Login [POST /users/login]

Login to an existing account

+ Request (application/json)

    + Body

            {
                "username": "jason",
                "password": "secret",
            }

+ Response 200

    + Headers

            Set-Cookie: nn-session-id:12345;nn-device-id:67890

+ Response 401 (application/json)

        {
            "status": 401,
            "message": "Username and password do not match"
        }

### Read User [GET /users/{id}]

+ Response 200 (application/json)

            {
                "id": 1,
                "username": "jason",
                "display_name": "Jason Maher",
                "email": "jason@jasonmaher.me",
                "avatar_url": "about:blank"
            }